'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Star, MapPin, Clock, Edit, Trash2, Filter, Search, Grid, List, SortAsc, SortDesc, ThumbsUp, MessageSquare, Calendar, Bell } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';

// Types for the reviews page
interface Review {
  id: string;
  type: 'written'; // written by user
  creationType: 'manual' | 'auto'; // manually written or automatically generated
  vendorId: string;
  vendorName: string;
  vendorImage: string;
  serviceName: string;
  rating: number;
  title: string;
  content: string;
  date: string; // ISO date string
  helpful: number;
  replies: number;
  status: 'published' | 'pending' | 'rejected';
  images?: string[];
  bookingId: string;
  serviceDate: string;
  price: number;
  category: string;
  autoGeneratedReason?: string; // reason for auto-generation (e.g., "No review submitted within 72 hours")
}

// Mock data for reviews
const mockReviews: Review[] = [
  {
    id: '1',
    type: 'written',
    creationType: 'manual',
    vendorId: '1',
    vendorName: 'Quick Fix Plumbing',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Emergency Pipe Repair',
    rating: 5,
    title: 'Excellent emergency service!',
    content: 'Called them at 2 AM for a burst pipe emergency. They arrived within 30 minutes and fixed everything professionally. The plumber was courteous and explained what he was doing. Highly recommend for emergencies!',
    date: '2024-01-20T14:30:00Z',
    helpful: 12,
    replies: 1,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center'],
    bookingId: 'BK001',
    serviceDate: '2024-01-20T02:00:00Z',
    price: 150,
    category: 'plumbing'
  },
  {
    id: '2',
    type: 'written',
    creationType: 'manual',
    vendorId: '4',
    vendorName: 'Bright Electric Co',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Smart Home Installation',
    rating: 4,
    title: 'Good work but expensive',
    content: 'The electrician did a great job installing our smart home system. Very knowledgeable about the latest technology. The only downside was the price - it was quite expensive for what we got. Quality work though.',
    date: '2024-01-15T10:15:00Z',
    helpful: 8,
    replies: 2,
    status: 'published',
    bookingId: 'BK002',
    serviceDate: '2024-01-15T09:00:00Z',
    price: 450,
    category: 'electrician'
  },
  {
    id: '3',
    type: 'written',
    creationType: 'auto',
    vendorId: '6',
    vendorName: 'Sparkle Cleaners',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Deep House Cleaning',
    rating: 5,
    title: 'Service completed successfully',
    content: 'Your service with Sparkle Cleaners has been completed successfully. This review was automatically generated as no review was submitted within 72 hours of service completion.',
    date: '2024-01-10T16:45:00Z',
    helpful: 15,
    replies: 1,
    status: 'published',
    bookingId: 'BK003',
    serviceDate: '2024-01-10T10:00:00Z',
    price: 200,
    category: 'home-cleaners',
    autoGeneratedReason: 'No review submitted within 72 hours'
  },
  {
    id: '4',
    type: 'written',
    creationType: 'manual',
    vendorId: '8',
    vendorName: 'AutoCare Pro',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Oil Change & Inspection',
    rating: 4,
    title: 'Professional and efficient service',
    content: 'The oil change was done quickly and professionally. The technician was knowledgeable and explained what they were doing. The waiting area was clean and comfortable. Will definitely use them again.',
    date: '2024-01-18T11:20:00Z',
    helpful: 3,
    replies: 0,
    status: 'published',
    bookingId: 'BK004',
    serviceDate: '2024-01-18T08:00:00Z',
    price: 85,
    category: 'automotive-repair'
  },
  {
    id: '5',
    type: 'written',
    creationType: 'manual',
    vendorId: '10',
    vendorName: 'Style Studio NYC',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Hair Styling & Color',
    rating: 5,
    title: 'Perfect for my wedding!',
    content: 'The stylist at Style Studio NYC did an amazing job on my hair for my wedding. The color was exactly what I wanted and the style held up all day. Worth every penny for such a special occasion.',
    date: '2024-01-05T13:30:00Z',
    helpful: 22,
    replies: 3,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center'],
    bookingId: 'BK005',
    serviceDate: '2024-01-05T10:00:00Z',
    price: 180,
    category: 'hair-nail-salon'
  },
  {
    id: '6',
    type: 'written',
    creationType: 'auto',
    vendorId: '12',
    vendorName: '24/7 Locksmith Pro',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Emergency Lockout Service',
    rating: 5,
    title: 'Service completed successfully',
    content: 'Your emergency lockout service has been completed successfully. This review was automatically generated as no review was submitted within 72 hours of service completion.',
    date: '2024-01-12T22:15:00Z',
    helpful: 5,
    replies: 1,
    status: 'published',
    bookingId: 'BK006',
    serviceDate: '2024-01-12T21:30:00Z',
    price: 120,
    category: 'locksmith',
    autoGeneratedReason: 'No review submitted within 72 hours'
  },
  {
    id: '7',
    type: 'written',
    creationType: 'auto',
    vendorId: '1',
    vendorName: 'Quick Fix Plumbing',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Drain Cleaning',
    rating: 5,
    title: 'Service completed successfully',
    content: 'Your drain cleaning service has been completed successfully. This review was automatically generated as no review was submitted within 72 hours of service completion.',
    date: '2024-01-08T14:20:00Z',
    helpful: 7,
    replies: 0,
    status: 'published',
    bookingId: 'BK007',
    serviceDate: '2024-01-08T11:00:00Z',
    price: 95,
    category: 'plumbing',
    autoGeneratedReason: 'No review submitted within 72 hours'
  },
  {
    id: '8',
    type: 'written',
    creationType: 'manual',
    vendorId: '15',
    vendorName: 'Premium Paint Pros',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'Interior House Painting',
    rating: 0,
    title: '',
    content: '',
    date: '2024-01-22T10:00:00Z',
    helpful: 0,
    replies: 0,
    status: 'pending',
    bookingId: 'BK008',
    serviceDate: '2024-01-22T08:00:00Z',
    price: 1200,
    category: 'painting-services'
  },
  {
    id: '9',
    type: 'written',
    creationType: 'manual',
    vendorId: '20',
    vendorName: 'TechFix Mobile',
    vendorImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    serviceName: 'iPhone Screen Repair',
    rating: 0,
    title: '',
    content: '',
    date: '2024-01-21T16:30:00Z',
    helpful: 0,
    replies: 0,
    status: 'pending',
    bookingId: 'BK009',
    serviceDate: '2024-01-21T14:00:00Z',
    price: 89,
    category: 'electronic-device-repair'
  }
];

const categories = [
  'All Categories',
  'Automotive Repair',
  'Automotive Detailing',
  'Adjuster',
  'Barber',
  'Body Shop',
  'Car Wash',
  'Contractors',
  'Dealership',
  'Electrician',
  'Electronic Device Repair',
  'HVAC Heating and Air Conditioning',
  'Home cleaners',
  'Hair/Nail Salon',
  'Landscaping',
  'Locksmith',
  'Medical Services',
  'Moving Services',
  'Pool Cleaning Services',
  'Pet Grooming',
  'Plumbing',
  'Painting Services',
  'Pest/Exterminating Services',
  'Security Installation',
  'Roofing Services',
  'Towing',
  'Tree Services'
];

export default function ReviewsPage() {
  const router = useRouter();
  const [reviews, setReviews] = useState<Review[]>(mockReviews);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [sortBy, setSortBy] = useState<'recent' | 'rating' | 'helpful' | 'price'>('recent');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('All Categories');
  const [creationType, setCreationType] = useState<'all' | 'manual' | 'auto'>('all');
  const [statusFilter, setStatusFilter] = useState<'all' | 'published' | 'pending'>('all');
  const [ratingFilter, setRatingFilter] = useState<number>(0);

  // Filter and sort reviews
  const filteredAndSortedReviews = reviews
    .filter(review => {
      // Search filter
      if (searchQuery && !review.title.toLowerCase().includes(searchQuery.toLowerCase()) && 
          !review.content.toLowerCase().includes(searchQuery.toLowerCase()) &&
          !review.vendorName.toLowerCase().includes(searchQuery.toLowerCase())) {
        return false;
      }
      
      // Category filter
      if (selectedCategory !== 'All Categories' && review.category !== selectedCategory.toLowerCase().replace(/\s+/g, '-')) {
        return false;
      }
      
      // Creation type filter
      if (creationType !== 'all' && review.creationType !== creationType) {
        return false;
      }
      
      // Status filter
      if (statusFilter !== 'all' && review.status !== statusFilter) {
        return false;
      }
      
      // Rating filter
      if (review.rating < ratingFilter) {
        return false;
      }
      
      return true;
    })
    .sort((a, b) => {
      let comparison = 0;
      
      switch (sortBy) {
        case 'recent':
          comparison = new Date(b.date).getTime() - new Date(a.date).getTime();
          break;
        case 'rating':
          comparison = b.rating - a.rating;
          break;
        case 'helpful':
          comparison = b.helpful - a.helpful;
          break;
        case 'price':
          comparison = b.price - a.price;
          break;
      }
      
      return sortOrder === 'asc' ? -comparison : comparison;
    });

  const deleteReview = (reviewId: string) => {
    setReviews(prev => prev.filter(review => review.id !== reviewId));
  };

  const editReview = (reviewId: string) => {
    router.push(`/reviews/edit/${reviewId}`);
  };

  const viewVendor = (vendorId: string) => {
    router.push(`/service/${vendorId}`);
  };

  const viewBooking = (bookingId: string) => {
    router.push(`/my-bookings?booking=${bookingId}`);
  };

  const toggleSortOrder = () => {
    setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc');
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const getTimeAgo = (dateString: string) => {
    const now = new Date();
    const date = new Date(dateString);
    const diffInDays = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));
    
    if (diffInDays === 0) return 'Today';
    if (diffInDays === 1) return 'Yesterday';
    if (diffInDays < 7) return `${diffInDays} days ago`;
    if (diffInDays < 30) return `${Math.floor(diffInDays / 7)} weeks ago`;
    return `${Math.floor(diffInDays / 30)} months ago`;
  };

  const renderStars = (rating: number) => {
    return Array.from({ length: 5 }, (_, i) => (
      <Star
        key={i}
        size={16}
        className={`${i < rating ? 'fill-yellow-400 text-yellow-400' : 'text-gray-300'}`}
      />
    ));
  };

  const ReviewCard = ({ review }: { review: Review }) => (
    <Card className="hover:shadow-lg transition-all duration-300 cursor-pointer group border border-gray-200 bg-white">
      <CardContent className="p-6">
        {/* Header */}
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            <img src={review.vendorImage} alt={review.vendorName} className="w-12 h-12 rounded-lg object-cover" />
            <div>
              <h3 className="font-semibold text-lg">{review.vendorName}</h3>
              <p className="text-sm text-gray-600">{review.serviceName}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {review.type === 'written' && review.creationType === 'manual' && review.status === 'published' && (
              <>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={(e) => {
                    e.stopPropagation();
                    editReview(review.id);
                  }}
                >
                  <Edit size={16} />
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  className="text-red-500 hover:text-red-700"
                  onClick={(e) => {
                    e.stopPropagation();
                    deleteReview(review.id);
                  }}
                >
                  <Trash2 size={16} />
                </Button>
              </>
            )}
          </div>
        </div>

                {/* Rating and Title */}
        <div className="mb-3">
          <div className="flex items-center gap-2 mb-2">
            {review.status === 'pending' ? (
              <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-200">
                <Clock size={14} className="mr-1" />
                Pending Review
              </Badge>
            ) : (
              <>
                <div className="flex items-center gap-1">
                  {renderStars(review.rating)}
                </div>
                {review.creationType === 'manual' ? (
                  <Badge variant="default">
                    You wrote
                  </Badge>
                ) : (
                  <Badge variant="outline" className="text-xs bg-orange-50 text-orange-700 border-orange-200">
                    Auto-Generated
                  </Badge>
                )}
              </>
            )}
          </div>
          {review.status === 'pending' ? (
            <h4 className="font-semibold text-lg mb-2 text-gray-500">Review Pending</h4>
          ) : (
            <h4 className="font-semibold text-lg mb-2">{review.title}</h4>
          )}
        </div>

        {/* Content */}
        {review.status === 'pending' ? (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-4">
            <p className="text-yellow-800 text-sm mb-3">
              <Clock size={16} className="inline mr-2" />
              Your service has been completed. Please write a review to help other customers.
            </p>
            <div className="flex gap-2">
              <Button size="sm" className="bg-yellow-600 hover:bg-yellow-700">
                Write Review
              </Button>
            </div>
          </div>
        ) : (
          <p className="text-gray-700 mb-4 line-clamp-3">{review.content}</p>
        )}

        {/* Images */}
        {review.images && review.images.length > 0 && (
          <div className="flex gap-2 mb-4">
            {review.images.map((image, index) => (
              <img
                key={index}
                src={image}
                alt={`Review image ${index + 1}`}
                className="w-16 h-16 rounded-lg object-cover"
              />
            ))}
          </div>
        )}

        {/* Service Details */}
        <div className="bg-gray-50 rounded-lg p-3 mb-4">
          <div className="flex items-center justify-between text-sm">
            <div className="flex flex-col gap-1">
              <div className="flex items-center gap-4">
                <span className="text-gray-600">Service Date: {formatDate(review.serviceDate)}</span>
                <span className="text-gray-600">Price: ${review.price}</span>
              </div>
              {review.autoGeneratedReason && (
                <span className="text-orange-600 text-xs italic">Reason: {review.autoGeneratedReason}</span>
              )}
            </div>
            <Button
              size="sm"
              variant="ghost"
              onClick={(e) => {
                e.stopPropagation();
                viewBooking(review.bookingId);
              }}
            >
              View Booking
            </Button>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between text-sm text-gray-500">
          <div className="flex items-center gap-4">
            <span>{getTimeAgo(review.date)}</span>
            <div className="flex items-center gap-1">
              <ThumbsUp size={14} />
              <span>{review.helpful} helpful</span>
            </div>
            {review.replies > 0 && (
              <div className="flex items-center gap-1">
                <MessageSquare size={14} />
                <span>{review.replies} replies</span>
              </div>
            )}
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={(e) => {
              e.stopPropagation();
              viewVendor(review.vendorId);
            }}
          >
            View Vendor
          </Button>
        </div>
      </CardContent>
    </Card>
  );

  const ReviewListItem = ({ review }: { review: Review }) => (
    <Card className="hover:shadow-md transition-all duration-300 cursor-pointer group border border-gray-200 bg-white">
      <CardContent className="p-4">
        <div className="flex items-start gap-4">
          <img src={review.vendorImage} alt={review.vendorName} className="w-16 h-16 rounded-lg object-cover flex-shrink-0" />
          
          <div className="flex-1 min-w-0">
            <div className="flex items-start justify-between mb-2">
              <div className="flex-1 min-w-0">
                <h3 className="font-semibold text-lg truncate">{review.vendorName}</h3>
                <p className="text-sm text-gray-600 mb-1">{review.serviceName}</p>
                <div className="flex items-center gap-2 mb-2">
                  {review.status === 'pending' ? (
                    <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-200">
                      <Clock size={14} className="mr-1" />
                      Pending Review
                    </Badge>
                  ) : (
                    <>
                      <div className="flex items-center gap-1">
                        {renderStars(review.rating)}
                      </div>
                      {review.creationType === 'manual' ? (
                        <Badge variant="default">
                          You wrote
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="text-xs bg-orange-50 text-orange-700 border-orange-200">
                          Auto-Generated
                        </Badge>
                      )}
                    </>
                  )}
                </div>
              </div>
              
              <div className="flex items-center gap-2 flex-shrink-0">
                {review.type === 'written' && review.creationType === 'manual' && review.status === 'published' && (
                  <>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={(e) => {
                        e.stopPropagation();
                        editReview(review.id);
                      }}
                    >
                      <Edit size={16} />
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      className="text-red-500 hover:text-red-700"
                      onClick={(e) => {
                        e.stopPropagation();
                        deleteReview(review.id);
                      }}
                    >
                      <Trash2 size={16} />
                    </Button>
                  </>
                )}
              </div>
            </div>
            
            {review.status === 'pending' ? (
              <h4 className="font-semibold text-base mb-2 text-gray-500">Review Pending</h4>
            ) : (
              <h4 className="font-semibold text-base mb-2">{review.title}</h4>
            )}
            {review.status === 'pending' ? (
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-3">
                <p className="text-yellow-800 text-sm mb-2">
                  <Clock size={14} className="inline mr-1" />
                  Your service has been completed. Please write a review.
                </p>
                <div className="flex gap-2">
                  <Button size="sm" className="bg-yellow-600 hover:bg-yellow-700 text-xs">
                    Write Review
                  </Button>
                </div>
              </div>
            ) : (
              <p className="text-gray-700 mb-3 line-clamp-2">{review.content}</p>
            )}
            
            <div className="flex items-center justify-between text-sm text-gray-500">
              <div className="flex items-center gap-4">
                <span>{getTimeAgo(review.date)}</span>
                <div className="flex items-center gap-1">
                  <ThumbsUp size={14} />
                  <span>{review.helpful} helpful</span>
                </div>
                {review.replies > 0 && (
                  <div className="flex items-center gap-1">
                    <MessageSquare size={14} />
                    <span>{review.replies} replies</span>
                  </div>
                )}
                <span>${review.price}</span>
              </div>
              
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={(e) => {
                    e.stopPropagation();
                    viewBooking(review.bookingId);
                  }}
                >
                  <Calendar size={14} className="mr-1" />
                  Booking
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={(e) => {
                    e.stopPropagation();
                    viewVendor(review.vendorId);
                  }}
                >
                  View Vendor
                </Button>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b sticky top-0 z-10 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-2xl font-bold text-gray-900">My Reviews</h1>
              <Badge variant="secondary" className="text-sm">
                {filteredAndSortedReviews.length} reviews
              </Badge>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                <Bell size={14} className="mr-1" />
                {filteredAndSortedReviews.filter(r => r.status === 'pending').length} pending reviews
              </Badge>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-6">
        {/* Filters and Controls */}
        <div className="bg-white rounded-lg border border-gray-200 p-4 mb-6">
          <div className="flex flex-wrap items-center gap-4">
            {/* Search */}
            <div className="flex-1 min-w-64">
              <div className="relative">
                <Search size={16} className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <Input
                  placeholder="Search reviews..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>

            {/* Category Filter */}
            <div className="min-w-48">
              <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {categories.map((category) => (
                    <SelectItem key={category} value={category}>
                      {category}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>



            {/* Creation Type Filter */}
            <div className="min-w-40">
              <Select value={creationType} onValueChange={setCreationType}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Creation Types</SelectItem>
                  <SelectItem value="manual">Manually Written</SelectItem>
                  <SelectItem value="auto">Auto-Generated</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Status Filter */}
            <div className="min-w-40">
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="published">Published</SelectItem>
                  <SelectItem value="pending">Pending Review</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Rating Filter */}
            <div className="min-w-40">
              <Select value={ratingFilter.toString()} onValueChange={(value) => setRatingFilter(parseInt(value))}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">Any Rating</SelectItem>
                  <SelectItem value="5">5 Stars</SelectItem>
                  <SelectItem value="4">4+ Stars</SelectItem>
                  <SelectItem value="3">3+ Stars</SelectItem>
                  <SelectItem value="2">2+ Stars</SelectItem>
                  <SelectItem value="1">1+ Star</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Sort */}
            <div className="flex items-center gap-2">
              <Select value={sortBy} onValueChange={setSortBy}>
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="recent">Recently Posted</SelectItem>
                  <SelectItem value="rating">Highest Rated</SelectItem>
                  <SelectItem value="helpful">Most Helpful</SelectItem>
                  <SelectItem value="price">Price</SelectItem>
                </SelectContent>
              </Select>
              <Button
                variant="outline"
                size="sm"
                onClick={toggleSortOrder}
                className="px-2"
              >
                {sortOrder === 'asc' ? <SortAsc size={16} /> : <SortDesc size={16} />}
              </Button>
            </div>

            {/* View Mode */}
            <div className="flex items-center gap-1 border rounded-lg p-1">
              <Button
                variant={viewMode === 'grid' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setViewMode('grid')}
                className="px-2"
              >
                <Grid size={16} />
              </Button>
              <Button
                variant={viewMode === 'list' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setViewMode('list')}
                className="px-2"
              >
                <List size={16} />
              </Button>
            </div>
          </div>
        </div>

        {/* Content */}
        {filteredAndSortedReviews.length === 0 ? (
          <div className="text-center py-12">
            <Star size={64} className="mx-auto text-gray-300 mb-4" />
            <h3 className="text-xl font-semibold text-gray-900 mb-2">No reviews found</h3>
            <p className="text-gray-600 mb-6">
                          {searchQuery || selectedCategory !== 'All Categories' || reviewType !== 'all' || creationType !== 'all' || ratingFilter > 0
              ? 'Try adjusting your filters to see more results.'
              : 'Start writing reviews for services you\'ve used to see them here.'}
            </p>
            <Button onClick={() => router.push('/my-bookings')}>
              View My Bookings
            </Button>
          </div>
        ) : (
          <div className={viewMode === 'grid' 
            ? 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6'
            : 'space-y-4'
          }>
            {filteredAndSortedReviews.map((review) => (
              viewMode === 'grid' 
                ? <ReviewCard key={review.id} review={review} />
                : <ReviewListItem key={review.id} review={review} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
} 