export default function PrivacyPage() {
  return (
    <div style={{ maxWidth: 800, margin: '40px auto', fontFamily: 'sans-serif' }}>
      <h1>Privacy Policy</h1>

      <p>
        Reliance values your privacy and is committed to handling personal information responsibly.
        This Privacy Policy explains what information we collect, how we use it, how we share it,
        and the choices available to you.
      </p>

      <h3>1. Information We Collect</h3>
      <ul>
        <li>Account information, including name, email address, phone number, and profile details.</li>
        <li>Service and booking details, including appointment and workflow-related records.</li>
        <li>Consent records and related consent event history.</li>
        <li>Service-related media submitted in connection with service workflows.</li>
        <li>Device, browser, IP, and related security and verification data.</li>
        <li>Communication and contact details used for notifications and support.</li>
        <li>Review, activity, and usage data generated through platform interactions.</li>
        <li>Moderation, Trust Score, public-proof, and account-status records generated by platform workflows.</li>
      </ul>

      <h3>2. How We Use Information</h3>
      <ul>
        <li>Provide and operate core platform functionality.</li>
        <li>Enable consent workflows and associated verification steps.</li>
        <li>Deliver service videos and customer access experiences.</li>
        <li>Detect, prevent, and investigate fraud, abuse, and security incidents.</li>
        <li>Maintain compliance logs and support dispute protection workflows.</li>
        <li>Provide customer support, analytics, and service improvements.</li>
        <li>Send account, invite, consent, service-record, review, security, and support communications.</li>
        <li>Operate moderation, public-proof, Trust Score, and launch-readiness controls.</li>
      </ul>

      <h3>3. Sharing of Information</h3>
      <p>
        We may share information as needed to operate the service workflow, including between
        vendors and customers where relevant to service records, consent, media access, and review
        flows. We may also share information with service providers that support hosting,
        communications, storage, analytics, and security operations. We may disclose information
        when required by law, legal process, or when reasonably necessary to protect users, safety,
        rights, or platform integrity.
      </p>

      <h3>4. Media and Consent Data</h3>
      <p>
        Service-related media and consent records may be stored and associated with relevant
        service records and accounts. These records may be retained and used for compliance,
        support, security, and dispute resolution purposes within the platform&apos;s operational
        workflows. Approved public media may appear on public vendor, service, discovery, or proof
        pages when the platform and moderation workflow allow it.
      </p>

      <h3>5. Public and Private Information</h3>
      <p>
        Public-facing areas may show provider profile details, services offered, approved public
        videos, public reviews, Trust Score context, and related proof signals. Private account
        details, consent logs, internal moderation notes, security records, and non-public media
        are used for platform operations and are not intended for general public display.
      </p>

      <h3>6. AI-Assisted Review</h3>
      <p>
        Reliance may use AI-assisted tools to help summarize, triage, or flag content for human
        review. AI assistance does not replace final human decisions for approval, moderation,
        vendor access, or account restrictions where manual review is required.
      </p>

      <h3>7. Data Retention</h3>
      <p>
        We retain information for as long as reasonably necessary for legitimate business and
        operational needs, including legal, security, compliance, support, and dispute-handling
        purposes. Retention periods may vary based on data type, context, and applicable
        obligations.
      </p>

      <h3>8. Security</h3>
      <p>
        We use commercially reasonable administrative, technical, and organizational safeguards to
        help protect personal information. No method of transmission or storage is completely
        secure, and we cannot guarantee absolute security.
      </p>

      <h3>9. Your Rights and Choices</h3>
      <p>
        Where applicable, you may request access to, correction of, or deletion of certain personal
        information. You may also manage communication preferences through available settings or by
        contacting support where those controls are supported.
      </p>

      <h3>10. Policy Updates</h3>
      <p>
        Reliance may update this Privacy Policy from time to time. When updates are made, we may
        post the revised policy through the platform or related communications. Continued use of
        the platform after updates become effective indicates acceptance of the revised policy.
      </p>
    </div>
  );
}
